compile_pdf:
  image: philipptempel/docker-ubuntu-tug-texlive:latest
  script:
    - latexmk
  artifacts:
    name: "${CI_PROJECT_PATH_SLUG}_${CI_COMMIT_REF_NAME}"
    paths:
      - '*.pdf'
  tags:
    - docker

